-- Delete the row
DELETE FROM ADDRESS;
DELETE FROM ADMIN;
DELETE FROM CREDENTIAL;

-- Reset the identity
DBCC CHECKIDENT ('ADDRESS', RESEED, 0);
DBCC CHECKIDENT ('ADMIN', RESEED, 0);
DBCC CHECKIDENT ('CREDENTIAL', RESEED, 0);