-- DELETE ALL ROW
-- PROCEED WITH CAUTION!
DELETE FROM ADDRESS;
DELETE FROM ADMIN;
DELETE FROM CREDENTIAL;
DELETE FROM DISTRIBUTOR;

DELETE FROM PRODUCT_LOG;
DELETE FROM PRODUCT_QUANTITY;
DELETE FROM PRODUCT_ACQUISITION;
DELETE FROM PRODUCT_PRICE;
DELETE FROM PRODUCT;
DELETE FROM [USER];
-- DELETE ALL ROW

SELECT * FROM ADDRESS;
SELECT * FROM CREDENTIAL;
SELECT * FROM ADMIN;

SELECT * FROM DISTRIBUTOR;
SELECT * FROM PRODUCT_LOG;
SELECT * FROM PRODUCT_QUANTITY;
SELECT * FROM PRODUCT_ACQUISITION;
SELECT * FROM PRODUCT_PRICE;
SELECT * FROM PRODUCT;

SELECT * FROM [USER];

-- Reset the identity
DBCC CHECKIDENT ('ADDRESS', RESEED, 0);
DBCC CHECKIDENT ('ADMIN', RESEED, 0);
DBCC CHECKIDENT ('CREDENTIAL', RESEED, 0);
DBCC CHECKIDENT ('DISTRIBUTOR', RESEED, 0);

DBCC CHECKIDENT ('PRODUCT_LOG', RESEED, 0);
DBCC CHECKIDENT ('PRODUCT_QUANTITY', RESEED, 0);
DBCC CHECKIDENT ('PRODUCT_ACQUISITION', RESEED, 0);
DBCC CHECKIDENT ('PRODUCT_PRICE', RESEED, 0);
DBCC CHECKIDENT ('PRODUCT', RESEED, 0);
DBCC CHECKIDENT ('USER', RESEED, 0);
-- Reset the identity

-- JOIN TABLES
SELECT * FROM ADDRESS AS AD
	INNER JOIN ADMIN AS A
	ON AD.A_ID = A.A_ID
	INNER JOIN CREDENTIAL AS C
	ON A.A_ID = C.A_ID;

SELECT * 
FROM PRODUCT P
LEFT JOIN PRODUCT_PRICE PP ON P.PROD_ID = PP.PROD_ID
LEFT JOIN PRODUCT_QUANTITY PQ ON P.PROD_ID = PQ.PROD_ID
LEFT JOIN PRODUCT_ACQUISITION PA ON P.PROD_ID = PA.PROD_ID
LEFT JOIN PRODUCT_LOG PL ON P.PROD_ID = PL.PROD_ID
LEFT JOIN DISTRIBUTOR D ON P.D_ID = D.D_ID;
-- JOIN TABLES


-- INSERT DISTRIBUTORS
INSERT INTO DISTRIBUTOR 
	VALUES('Apple', DEFAULT, DEFAULT), 
	('Samsung', DEFAULT, DEFAULT),
	('Oppo', DEFAULT, DEFAULT),
	('Xiaomi', DEFAULT, DEFAULT)


SELECT PROD_MAKE, PROD_MODEL, PROD_IMG, PP.PP_AMOUNT, PQ.PQ_QTY
	FROM PRODUCT_PRICE AS PP
	INNER JOIN PRODUCT  
	ON PRODUCT.PROD_ID = PP.PROD_ID
	INNER JOIN
	PRODUCT_QUANTITY AS PQ
	ON PQ.PROD_ID = PRODUCT.PROD_ID;

UPDATE PRODUCT_QUANTITY SET PQ_QTY = 12 WHERE PQ_ID = 3;

SELECT P.PROD_ID, P.PROD_MAKE, P.PROD_MODEL, P.PROD_WARRANTY, P.PROD_DESC, PQ.PQ_QTY 
FROM PRODUCT AS P
INNER JOIN PRODUCT_QUANTITY AS PQ ON P.PROD_ID = PQ.PROD_ID
INNER JOIN PRODUCT_PRICE AS PP ON P.PROD_ID = PP.PROD_ID;

SELECT *
FROM [USER] AS U
INNER JOIN CREDENTIAL AS C ON U.USER_ID = C.USER_ID
INNER JOIN ADDRESS AS A ON U.USER_ID = A.USER_ID;